--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/IvanCraft623/RankSystem
build-by-default: true
branches:
- PM3
- PM4
- PM5
projects:
  RankSystem:
    path: ""
    lint:
      phpstan: false
    libs:
      - src: LatamPMDevs/Commando/Commando
        version: ^3.1.1
        branch: pm5
      - src: LatamPMDevs/ConfigUpdater/ConfigUpdater
        version: ^2.0.1
        branch: master
      - src: LatamPMDevs/UpdateNotifier/UpdateNotifier
        version: ^3.0.0
      - src: IvanCraft623/languages/languages
        version: ^0.0.3
      - src: LatamPMDevs/FormAPI/libFormAPI
        version: ^2.1.1
      - src: poggit/libasynql/libasynql
        version: ^4.1.6
...
