name: Build Phar

on:
  workflow_call:
    inputs:
      stage-poggit:
        description: Whether to stage the build on Poggit CI
        type: boolean
        default: false
    outputs:
      plugin-name:
        value: ${{ jobs.build.outputs.plugin-name }}
      plugin-version:
        value: ${{ jobs.build.outputs.plugin-version }}
      pm-version:
        value: ${{ jobs.build.outputs.pm-version }}
      artifact-name:
        value: ${{ jobs.build.outputs.artifact-name }}

jobs:
  build:
    name: Phar build
    runs-on: ubuntu-latest
    outputs:
      plugin-name:    ${{ steps.plugin-info.outputs.PLUGIN_NAME }}
      plugin-version: ${{ steps.plugin-info.outputs.PLUGIN_VERSION }}
      pm-version:     ${{ steps.plugin-info.outputs.PM_VERSION }}
      artifact-name:  ${{ steps.plugin-info.outputs.PLUGIN_NAME }}-phar
    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: pmmp/setup-php-action@3.2.0
        with:
          php-version: 8.2
          install-path: ./bin

      - name: Get plugin info
        id: plugin-info
        run: |
          PM_VERSION=$(php -r "
            \$api = yaml_parse_file('plugin.yml')['api'];
            echo is_array(\$api) ? implode(', ', \$api) : \$api;
          ")
          PLUGIN_VERSION=$(php -r "echo yaml_parse_file('plugin.yml')['version'];")
          PLUGIN_NAME=$(php -r "echo yaml_parse_file('plugin.yml')['name'];")
          echo "PM_VERSION=$PM_VERSION"         >> $GITHUB_OUTPUT
          echo "PLUGIN_VERSION=$PLUGIN_VERSION" >> $GITHUB_OUTPUT
          echo "PLUGIN_NAME=$PLUGIN_NAME"       >> $GITHUB_OUTPUT

      - name: Install Composer dependencies
        run: composer install --no-dev --prefer-dist --no-interaction --classmap-authoritative --ignore-platform-reqs

      - uses: SOF3/pharynx@v0.2
        id: pharynx
        with:
          stage-poggit: ${{ inputs.stage-poggit }}

      - name: Compress phar
        run: |
          php -dphar.readonly=0 -r "
            \$phar = new Phar('${{ steps.pharynx.outputs.output-phar }}');
            \$phar->compressFiles(Phar::GZ);
          "

      - name: Rename phar
        run: |
          mv ${{ steps.pharynx.outputs.output-phar }} \
             "$RUNNER_TEMP/${{ steps.plugin-info.outputs.PLUGIN_NAME }}.phar"

      - name: Upload phar artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.plugin-info.outputs.PLUGIN_NAME }}-phar
          path: ${{ runner.temp }}/${{ steps.plugin-info.outputs.PLUGIN_NAME }}.phar
          retention-days: 1
