name: Nightly

on:
  push:
    branches: [PM5]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-name:  ${{ steps.build.outputs.artifact-name }}
      plugin-name:    ${{ steps.build.outputs.plugin-name }}
      plugin-version: ${{ steps.build.outputs.plugin-version }}
      pm-version:     ${{ steps.build.outputs.pm-version }}
    steps:
      - uses: actions/checkout@v4
      - uses: axolotl-pm/pmmp-plugin-actions/build-phar@main
        id: build
        with:
          php-version: '8.2'
          stage-poggit: true

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: axolotl-pm/pmmp-plugin-actions/publish-nightly@main
        with:
          artifact-name:  ${{ needs.build.outputs.artifact-name }}
          plugin-name:    ${{ needs.build.outputs.plugin-name }}
          plugin-version: ${{ needs.build.outputs.plugin-version }}
          pm-version:     ${{ needs.build.outputs.pm-version }}
